### ISSUE TITLE
Links Intro Episode

### ISSUE THREAD

**Issue by rcurty** [UCSBCarpentry/2024-02-27-ucsb-webscraping#1]
https://ucsbcarpentry.github.io/2024-02-27-ucsb-webscraping/01-introduction/index.html

Replace all external links, use target blank instead.

Parliament of Canada broken link http://www.parl.gc.ca/Parliamentarians/en/members). Update to:
https://www.ourcommons.ca/members/en/search?view=list
Export feature at the bottom now (for screenshot)

UK House of Commons new website: https://members.parliament.uk/members/commons

**Comment by srerickson** [comment]
I updated the Canadian parliament example (https://github.com/UCSBCarpentry/2024-02-27-ucsb-webscraping/commit/d005e12d32d2eb35eed99174c341206487d6b03f). Unfortunately, the new site's html isn't as nicely labelled as it used to be, so the example make less sense. 

I'll work on UK House of Commons example next.
